### ISSUE TITLE
Extracting Annotations Fails

### ISSUE THREAD

**Issue by evant** [evant/holdr#22]
```
Not extracting annotations (compilation problems encountered)
Error:/home/evan/android/Holdr/sample-library/src/main/java/me/tatarka/samplelibrary/LibraryExampleFragment.java:8: The import me.tatarka.samplelibrary.holdr cannot be resolved
```

It looks like the the generated Holdr classes aren't added to the classpath used by the annotation extractor. I'm using `variant.registerJavaGeneratingTask(task, outputDir)` though, so could this a bug in the android gradle plugin?

**Comment by IgorGanapolsky** [comment]
@evant gradle plugin 0.14.3?  That is ages old!

**Comment by evant** [comment]
And so is this issue, I fail to see your point

**Comment by IgorGanapolsky** [comment]
@evant "Nov 19, 2014" is not considered "ages".

**Comment by evant** [comment]
And the issue I linked to was closed on Nov 18, why are you commenting on this old issue?
