### ISSUE TITLE
Holdr generating invalid classes from appcompat-v7 (21) 

### ISSUE THREAD

**Issue by loeschg** [evant/holdr#37]
![screenshot 2014-10-22 11 50 23](https://cloud.githubusercontent.com/assets/766021/4739249/323867cc-5a03-11e4-8c65-c44d9320ca39.png)

This is resulting in compilation errors. One of the generated lines is as follows:

    public android.widget.ImageView android:icon2;

I attempted to add the `holdr.defaultInclude false` as recommended in the docs, though I'm not sure it's working/if I've put it in the right place in my build.gradle.

**Comment by intrications** [comment]
Is version 1.1.2 of the plugin likely to be released soon? I'm still having this problem sometimes.

**Comment by evant** [comment]
Released! Sorry, that took far longer than it should have.

**Comment by intrications** [comment]
@evant Sorry, will the update be uploaded to the JetBrains plugin repo?

The link to the plugin zip now leads to a 404: https://github.com/evant/holdr/blob/master/intellij-plugin/intellij-plugin.zip?raw=true

**Comment by evant** [comment]
It's uploaded and waiting for approval. The zip is no longer in the repo since I changed my build process. I still need to update the README with instructions on how to build it if you want to install it manually.
