### ISSUE TITLE
Holdr support bind data

### ISSUE THREAD

**Issue by CaoManhDat** [evant/holdr#49]
Holder cand bind data is an interesting thing :+1: 
## In layout file
```
<!-- hand.xml -->
<?xml version="1.0" encoding="utf-8"?>

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical" 
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:id="@+id/username"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
    <TextView
        android:id="@+id/password"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>

</LinearLayout>
```

## Bean class

```
public class User{
    private String username;
    private String password;
}
```

and holdr support some thing like this

```
holdr = new Holdr_Hand(rootView);
holdr.bind(user);
```

**Comment by evant** [comment]
I don't think this buys you enough to be worth it. Seems kinda textview-specific doesn't it? I can't think of any good binds to other views. Do you really have a lot of layouts that are a bunch of TextViews that need to be set like that? Also, unless we were to use reflection, the type of class to pass in would have to be somehow annotated and those fields be made public or have getters. You can duplicate this behavior in a much more flexible way by subclassing the holdr class, is that not good enough?
```java
public class MyHand extends Holdr_Hand {
    public MyHand(View view) {
        super(view);
    }

    public void bind(User user) {
        username.setText(user.getUsername());
        password.setText(user.getPassword());
    }
}
```

**Comment by CaoManhDat** [comment]
It can be binding for any kind of view, like ImageView, TextField.. This thing will make holdr become an essential for any android application.

**Comment by evant** [comment]
For ImageView, you mean like a URL? You'd want to use an image loading library like Picasso for that. For EditText, would you be binding to the text content or the hint? This solution is simply too inflexible and requires a significant amount of work because every single view to bind to would have to be special-cased.

**Comment by CaoManhDat** [comment]
youre right, it kinda textview specific.
